### ISSUE TITLE
[infra] fix: automatically restart `tournesol-website-analytics` when the Docker config changes 

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1347]
**only relevant if** https://github.com/tournesol-app/tournesol/pull/1340 **is merged**

---

### Context

When the Docker configuration file `/etc/docker/daemon.json` is updated, the containers of Plausible Analytics are not automatically removed and re-created. As a consequence, some configuration modifications like a change of the default logging driver won't automatically be effective after a deployment. A manual restart of `tournesol-website-analytics` with `systemctl` is required to apply the changes.

### technical details

If following Ansible task updates the `/etc/docker/daemon.json`, a restart of the service should be triggered. Note that notifying a handler with only `notify` and `listen` won't work properly. The first time a VM is provisioned, the Plausible Analytics service doesn't exist when the following task is running. Triggering the restart of a non-existing service will make the deployment fail. The restart should be conditioned by the existence of the service.

```yml
- name: Copy the Docker settings
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
  notify:
    - Restart Docker
```
